// <auto-generated />
using System;
using BaiKiemTra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiKiemTra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiKiemTra.Models.EventCategory_BIT240074", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventCategories_BIT240074");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các sự kiện hội nghị, hội thảo",
                            Name = "Hội nghị"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các sự kiện thi đấu, cuộc thi",
                            Name = "Hội thi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các sự kiện tiệc cưới",
                            Name = "Tiệc cưới"
                        });
                });

            modelBuilder.Entity("BaiKiemTra.Models.EventImage_BIT240074", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventImages_BIT240074");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            ImageUrl = "https://picsum.photos/400/300?random=1",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            ImageUrl = "https://picsum.photos/400/300?random=2",
                            IsThumbnail = false
                        },
                        new
                        {
                            Id = 3,
                            EventId = 2,
                            ImageUrl = "https://picsum.photos/400/300?random=3",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 4,
                            EventId = 3,
                            ImageUrl = "https://picsum.photos/400/300?random=4",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 5,
                            EventId = 4,
                            ImageUrl = "https://picsum.photos/400/300?random=5",
                            IsThumbnail = true
                        },
                        new
                        {
                            Id = 6,
                            EventId = 5,
                            ImageUrl = "https://picsum.photos/400/300?random=6",
                            IsThumbnail = true
                        });
                });

            modelBuilder.Entity("BaiKiemTra.Models.Event_BIT240074", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventCategoryId");

                    b.HasIndex("Location", "StartDate", "EndDate");

                    b.ToTable("Events_BIT240074");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hội nghị về phát triển web hiện đại",
                            EndDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventCategoryId = 1,
                            Location = "TP. Hồ Chí Minh",
                            Name = "Hội nghị phát triển web 2026",
                            Price = 500000m,
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cuộc thi lập trình dành cho sinh viên",
                            EndDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventCategoryId = 2,
                            Location = "Hà Nội",
                            Name = "Cuộc thi lập trình quốc tế",
                            Price = 0m,
                            StartDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tiệc cưới lãng mạn",
                            EndDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventCategoryId = 3,
                            Location = "Đà Nẵng",
                            Name = "Tiệc cưới John & Mary",
                            Price = 1000000m,
                            StartDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hội nghị về trí tuệ nhân tạo",
                            EndDate = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventCategoryId = 1,
                            Location = "TP. Hồ Chí Minh",
                            Name = "Hội thảo AI",
                            Price = 300000m,
                            StartDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cuộc thi thiết kế đồ họa sáng tạo",
                            EndDate = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventCategoryId = 2,
                            Location = "Hà Nội",
                            Name = "Cuộc thi thiết kế đồ họa",
                            Price = 200000m,
                            StartDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BaiKiemTra.Models.EventImage_BIT240074", b =>
                {
                    b.HasOne("BaiKiemTra.Models.Event_BIT240074", "Event_BIT240074")
                        .WithMany("EventImages_BIT240074")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event_BIT240074");
                });

            modelBuilder.Entity("BaiKiemTra.Models.Event_BIT240074", b =>
                {
                    b.HasOne("BaiKiemTra.Models.EventCategory_BIT240074", "EventCategory_BIT240074")
                        .WithMany("Events_BIT240074")
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCategory_BIT240074");
                });

            modelBuilder.Entity("BaiKiemTra.Models.EventCategory_BIT240074", b =>
                {
                    b.Navigation("Events_BIT240074");
                });

            modelBuilder.Entity("BaiKiemTra.Models.Event_BIT240074", b =>
                {
                    b.Navigation("EventImages_BIT240074");
                });
#pragma warning restore 612, 618
        }
    }
}
